### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by hoosierEE** [iubrain/distance#9]
let's do this

- [ ] perfect colors
- [ ] "works" on all major desktop browsers 
- [ ] "works" on all major mobile browsers
- [ ] distance is accurate
- [ ] direction is accurate
- [ ] feature list complete

**Comment by iubrain** [comment]
What are the features in "feature list"?

**Comment by hoosierEE** [comment]
Dream Big:

* Background color fades to front-facing camera view, take your picture at some distance with the compass overlaid, shared instantly to social media
* Light show synchronized with the actual lights on the brain, control them from your phone

Dream Modestly:

* home button takes you to psych.indiana.edu
* twitter button takes you to iubrain's twitter feed
* Light show when your distance to the brain goes below X
